//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenWrap.Tests.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenWrap.Tests.Repositories.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;feed xml:lang=&quot;en-us&quot; xmlns:pkg=&quot;http://schemas.microsoft.com/packaging/2010/07/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Demo Feed&lt;/title&gt;
        ///  &lt;subtitle type=&quot;text&quot;&gt;ASP.NET package feed&lt;/subtitle&gt;
        ///  &lt;id&gt;uuid:e25c6f6c-6108-4b8b-b4ab-5b23af6ea5d7;id=1282&lt;/id&gt;
        ///  &lt;rights type=&quot;text&quot;&gt;Copyright 2010&lt;/rights&gt;
        ///  &lt;updated&gt;2010-10-11T07:08:57Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Demo&lt;/name&gt;
        ///    &lt;uri&gt;http://www.demofeed.com&lt;/uri&gt;
        ///    &lt;email&gt;person@demofeed. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string feed {
            get {
                return ResourceManager.GetString("feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;feed xml:base=&quot;http://173.203.67.148/current/odata/v1/&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;Packages&lt;/title&gt;
        ///  &lt;id&gt;http://173.203.67.148/current/odata/v1/Packages&lt;/id&gt;
        ///  &lt;updated&gt;2010-10-11T08:13:37Z&lt;/updated&gt;
        ///  &lt;link rel=&quot;self&quot; title=&quot;Packages&quot; href=&quot;Packages&quot; /&gt;
        ///  &lt;entry&gt;
        ///    &lt;id&gt;http://173.203.67.148/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string feedodata {
            get {
                return ResourceManager.GetString("feedodata", resourceCulture);
            }
        }
        
        internal static byte[] TestPackageOld {
            get {
                object obj = ResourceManager.GetObject("TestPackageOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
