//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.ProjectModel.drivers.file {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.ProjectModel.drivers.file.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 10.00
        ///# Visual Studio 2008
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;T4CssWeb&quot;, &quot;T4CssWeb\T4CssWeb.csproj&quot;, &quot;{9E6CF849-146B-4338-9FC1-2BAA6576B0BA}&quot;
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;lib&quot;, &quot;lib&quot;, &quot;{CB4AA2D7-A52B-4A21-A1EF-A8BB445E66FB}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		.Less-License.txt = .Less-License.txt
        ///		dotless.Core.dll = dotless.Core.dll
        ///	EndProjectSection
        ///EndProject
        ///Global
        ///	GlobalSec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dotless {
            get {
                return ResourceManager.GetString("dotless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Common&quot;, &quot;Common&quot;, &quot;{83F17668-79F5-46CB-9C33-AF30F48FAAD8}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		CONTRIBUTORS - READ ME!.txt = CONTRIBUTORS - READ ME!.txt
        ///		FluentKey.snk = FluentKey.snk
        ///	EndProjectSection
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Examples&quot;, &quot;Examples&quot;, &quot;{3D285AE0-E5CF-4923-B543-0D70E5C6DE18}&quot;
        ///EndProject
        ///Project(&quot;{FAE0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fluentnhibernate {
            get {
                return ResourceManager.GetString("fluentnhibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;GitAspx&quot;, &quot;GitAspx\GitAspx.csproj&quot;, &quot;{3A732219-72CE-49B8-84F6-FE74E3762EE7}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;GitAspx.Tests&quot;, &quot;GitAspx.Tests\GitAspx.Tests.csproj&quot;, &quot;{A1C3A88B-8C35-4677-B83F-E61FEAAD604A}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gitdotaspx {
            get {
                return ResourceManager.GetString("gitdotaspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{F2A71F9B-5D33-465A-A702-920D77279786}&quot;) = &quot;IronJS&quot;, &quot;IronJS\IronJS.fsproj&quot;, &quot;{9E257324-94E7-49AF-AE83-718288E925D8}&quot;
        ///EndProject
        ///Project(&quot;{F2A71F9B-5D33-465A-A702-920D77279786}&quot;) = &quot;REPL&quot;, &quot;Tools\REPL\REPL.fsproj&quot;, &quot;{0F78334F-EA74-4C5C-8232-B7D329BE2226}&quot;
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Files&quot;, &quot;Files&quot;, &quot;{7E895BE2-763D-4384-B17C-4EEC183D7479}&quot;
        ///	ProjectSection(SolutionItems) = preP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ironjs {
            get {
                return ResourceManager.GetString("ironjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Tests&quot;, &quot;Tests&quot;, &quot;{74E5ECE0-06B4-401C-AEBA-E8DD53E17943}&quot;
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Symbols&quot;, &quot;Symbols&quot;, &quot;{929D5B3B-E29A-40CC-93D8-0FF43A6F9FA1}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;Mono.Cecil&quot;, &quot;Mono.Cecil.csproj&quot;, &quot;{D68133BD-1E63-496E-9EDE-4FBDBF77B486}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monocecil {
            get {
                return ResourceManager.GetString("monocecil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Solution Items&quot;, &quot;Solution Items&quot;, &quot;{2EEC5803-1935-413B-AC35-7E5575CD59B6}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		src\CommonInfo.cs = src\CommonInfo.cs
        ///	EndProjectSection
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;OpenRasta&quot;, &quot;src\OpenRasta\OpenRasta.csproj&quot;, &quot;{C3ED9CCE-A140-4D0F-AE00-FBBF4CD27647}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string openrasta {
            get {
                return ResourceManager.GetString("openrasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Build&quot;, &quot;Build&quot;, &quot;{20503E9F-CA3D-496B-8842-B1FE7D39B1E7}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		..\build\openwrap.proj = ..\build\openwrap.proj
        ///		..\build\self-build.test = ..\build\self-build.test
        ///		..\version = ..\version
        ///	EndProjectSection
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;Common&quot;, &quot;Common&quot;, &quot;{FF7BA218-B2A1-462A-8F51-153337027 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string openwrap {
            get {
                return ResourceManager.GetString("openwrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{{{0}}}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///    &lt;RootNamespace&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_classlib {
            get {
                return ResourceManager.GetString("project_classlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;RestSharp&quot;, &quot;RestSharp\RestSharp.csproj&quot;, &quot;{2ECECFBF-5F3E-40EE-A963-72336DC7ABE2}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;RestSharp.Tests&quot;, &quot;RestSharp.Tests\RestSharp.Tests.csproj&quot;, &quot;{1464E4AC-18BB-4F23-8A0B-68196F9E1871}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;RestSharp.IntegrationTests&quot;, &quot;RestSharp.IntegrationTests\Res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string restsharp {
            get {
                return ResourceManager.GetString("restsharp", resourceCulture);
            }
        }
    }
}
