[assembly: System.Reflection.AssemblyCompany("Caffeine IT / naughtyProd Limited")]
[assembly: System.Reflection.AssemblyProduct("OpenWrap package management")]
[assembly: System.Reflection.AssemblyCopyright("Copyright � naughtyProd Limited 2009-2011")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Reflection.AssemblyVersion("2.0.0.*")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0.1")]
